### ISSUE TITLE
Can it apply to xaf.web?

### ISSUE THREAD

**Issue by comsher** [codecentral-examples/E4829-How-to-apply-theme-to-DevExpress-ASPNET-Control-Descendant#1]
Hello, your invention is very good. Can dynamically generated pages be applicable? For example, XAF. Web.

**Comment by Alexgoon** [comment]
This is a test example repository. To get a response from the DevExpress support team, please ask your question at [http://www.devexpress.com/ask](http://www.devexpress.com/ask)
